### ISSUE TITLE
Improve and simplify Harvest execution and configuration to only manage Registry collection

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/harvest#16]
- [x] Remove search index creation (this will be created / managed by separate tool)
- [x] Remove SolrJ push
- [x] Create "solr docs" for batch processing to registry index
- [ ] Update docs to show how to run registry-mgr and push solr docs to registry collection
- [x] Simplify config to consolidate all the different product types to 1 product type and software will registry all PDS4 XML products (not necessarily sure how to ensure it is PDS4?)
- [x] Cleanup and pull out old dead code
